<?php

/**
 * @file
 * Contains ecedi_basics.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_help().
 */
function ecedi_basics_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    // Main module help for the ecedi basics module.
    case 'help.page.ecedi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide generic tools and helpers to develop faster.') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ecedi_basics_form_user_form_alter(&$form, $form_state, $form_id) {
  $current_user = \Drupal::currentUser();
  $user = User::load($current_user->id());

  // Allow a user to assign roles (excluding admin).
  if (!$user->hasRole('administrator') && $user->hasPermission('assign roles')) {
    $form['account']['roles']['#access'] = TRUE;
    unset($form['account']['roles']['#options']['administrator']);
  }
}
